export const EvolutionTreeMapping = {
    'egg': ['toeny', 'finny', 'wingin'],
    'toeny': ['meerkat', 'turtle' , 'tapir' ],
    'turtle': ['tortoise','armadillo' , 'pangolin'],
    'meerkat': ['bear', 'red panda', 'kangaroo'],
    'tapir': ['elephant', 'anteater', 'rhino'],
    'wingin': ['na\' vi', 'bat', 'duck'],
    'na\' vi': ['biblical angel', 'flying fish', 'butterfly'],
    'bat': ['flying squirrel', 'wyvern', 'manta ray'],
    'duck': ['phoenix', 'pegasus', 'griffin'],
    'finny': ['snake', 'piranha', 'beta fish'],
    'snake': ['hydra', 'seahorse', 'eel'],
    'piranha': ['puffer fish', 'shark', 'angler fish'],
    'beta fish': ['swordfish', 'lionfish',  'frilled lizard'],
}
