export const EvolutionMapping = {
	egg: require('../images/Egg.png'),
	toeny: require('../images/Evolutions/Legs.png'),
	finny: require('../images/Evolutions/Fin.png'),
	wingin: require('../images/Evolutions/Wing.png'),
	meerkat: require('../images/Evolutions/Meerkat.png'),
	turtle: require('../images/Evolutions/Turtle.png'),
	tapir: require('../images/Evolutions/Tapir.png'),
	tortoise: require('../images/Evolutions/Tortoise.png'),
	armadillo: require('../images/Evolutions/Armadillo.png'),
	pangolin: require('../images/Evolutions/Pangolin.png'),
	bear: require('../images/Evolutions/Bear.png'),
	'red panda': require('../images/Evolutions/RedPanda.png'),
	kangaroo: require('../images/Evolutions/Kangaroo.png'),
	elephant: require('../images/Evolutions/Elephant.png'),
	anteater: require('../images/Evolutions/AntEater.png'),
	rhino: require('../images/Evolutions/Rhino.png'),
	"na' vi": require('../images/Evolutions/MultiWing.png'),
	bat: require('../images/Evolutions/Bat.png'),
	duck: require('../images/Evolutions/Bird.png'),
	'biblical angel': require('../images/Evolutions/BiblicalAngel.png'),
	'flying fish': require('../images/Evolutions/FlyingFish.png'),
	butterfly: require('../images/Evolutions/Butterfly.png'),
	'flying squirrel': require('../images/Evolutions/FlyingSquirrel.png'),
	wyvern: require('../images/Evolutions/Wyvern.png'),
	'manta ray': require('../images/Evolutions/MantaRay.png'),
	phoenix: require('../images/Evolutions/Phoenix.png'),
	pegasus: require('../images/Evolutions/Pegasus.png'),
	griffin: require('../images/Evolutions/Griffin.png'),
	snake: require('../images/Evolutions/Snake.png'),
	piranha: require('../images/Evolutions/Piranha.png'),
	'beta fish': require('../images/Evolutions/BetaFish.png'),
	hydra: require('../images/Evolutions/Hydra.png'),
	seahorse: require('../images/Evolutions/Seahorse.png'),
	eel: require('../images/Evolutions/Eel.png'),
	'puffer fish': require('../images/Evolutions/PufferFish.png'),
	shark: require('../images/Evolutions/Shark.png'),
	'angler fish': require('../images/Evolutions/AnglerFish.png'),
	swordfish: require('../images/Evolutions/SwordFish.png'),
	lionfish: require('../images/Evolutions/LionFish.png'),
	'frilled lizard': require('../images/Evolutions/FrilledLizard.png'),
};
